# student.conf
# This file is used for TA grading purposes.
# Please fill out your personal information correctly.
# GITHUB_USERNAME must match the account you use to push to GitHub Classroom.

STUDENT_ID="b12902041"
STUDENT_NAME="陳冠均"
GITHUB_USERNAME="brian731016"
